### PR TITLE
Replace Ad HTML Page

### PR DESCRIPTION
**Pull request by amirajas**

### CODE REVIEW

**Review by nbriz — CHANGES_REQUESTED** [review]
in the browser this all looks good, but i have some code questions/suggestions:

first, [this appears to be a mistake](https://github.com/net-art-and-cultures/the-toolkit/blob/53bb5425632ff2ebe715111b364688582a90f7e7/server/www/index.html#L30), right? id's should not be names of images. was this meant to be an `` tag? or should this have a different id?

in ur stylesheet i noticed a few classes that aren't being used in any of ur html pages (as far as i can tell), there's a `button_1` class that i don't think is used anywhere && also a few  CSS rules applied to a `showcase` id... but this also doesn't seem to exist. if this is old code then it's best to remove this from the style sheet.

**Comment by amirajas** [comment]
I think we're gonna use the buttons in the future but for the most part Erin wrote the code for the css and base of the index page.

**Review by nbriz — CHANGES_REQUESTED** [review]
this is looking good, but there are still a couple of things that need addressing before i can accept this pull request:

first, i don't understand what all the 'showcase sidebar' classes in the styles.css page are for, is this something yawwwl are prepping for later? b/c i don't see them being applied to any of the HTML pages. u should remove (or at least comment out, if u plan on using it later) any un-used CSS from the stylesheet before merging it w/the class repo.

also, the `index.html` page && the `replaceads.html` page both have this line of code in their head:
```html
<link rel="server" href="./js/server.js">
```
while i understand the impulse, this actually isn't how the server works. it's not the html pages that include the server, it's the other way around. when a "client" (ie. browser on someones phone/computer) requests a website, this request goes to the server.js file. the server knows about the html pages && sends the appropriate page back to the client when requested.

lastly, bootstrap is a great library, but right now it doesn't seem like it's being used by any of the HTML pages, i would remove it from the repo until u actually make use of it somewhere.

**Comment by nbriz** [comment]
hey @amirajas , b/c we need to keep things moving fwd in class, i'm going to accept this pull request (even though it still needs the revisions i mentioned above) so that Erin can pull ur changes && avoid a conflict. then i'm going to have Erin make the revisions i requested above.

we'll be doing this in class now, so just make sure u pull changes before the next time u work on anything

**Pull request merged**
